### PR TITLE
More user-friendly command-line usage

### PR DESCRIPTION
**Pull request by ritiek**
Input text can now either be a command-line argument or path to text file. Also makes it possible to set custom bias, position, specify style and add RGB color codes to resulting output image.

For converting output image to blue ink:
```
python3 get_hand.py -t "Hello World!" -c "0,0,150"
```

For choosing the 2nd style as on the website:
```
python3 get_hand.py -t "Hello World!" -s 1
```

For full list of available options:
```
python3 get_hand.py --help
```

### CODE REVIEW

**Comment by theSage21** [comment]
@ritiek is this PR ready for merge?

**Comment by ritiek** [comment]
Yep, I guess it is ready to merge. Let me know if anything needs refactoring.

**Comment by theSage21** [comment]
@ritiek  you've tested it locally? Would be nice if you updated the screenshots + README

**Comment by ritiek** [comment]
Yeah, haven't ran into a problem so far with local tests.

I've also updated the README, removed the old example image and added new ones via URL.

**Pull request merged**
